### ISSUE TITLE
addGISTHeaderComment() performance issue

### ISSUE THREAD

**Issue by drtobybrown** [geckos-survey/gist-geckos#48]
This code to modify the headers uses a lot of memory and is very slow to execute. The issue is that it loads the HDU - including data - of every FITS file into memory when all that's needed is the header. 
https://github.com/geckos-survey/gist-geckos/blob/fab2d104a5920d68d2da2b03e1216967f458bcb2/gistPipeline/auxiliary/_auxiliary.py#L119-L130

I suggest modifying the header of the first HDU (ie., ext=0) rather that all HDUs which can be hundreds for some files. This improved the pipeline run time by 4x for me.

e.g.,

```
def addGISTHeaderComment(config):
    """
    Add a GIST header comment in all fits output files.
    """
    filelist = glob.glob(os.path.join(config["GENERAL"]["OUTPUT"], "*.fits"))

    for file in filelist:
        if "Generated with the GIST pipeline" not in str(fits.getheader(file)):
            fits.setval(file, "COMMENT", value="", ext=0)
```

**Comment by ameliafm612** [comment]
Done!
